name: Heroku Deploy
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment variable
        env:
          POSTGRES_DB: ${{ secrets.HEROKU_POSTGRES_DB }} 
          POSTGRES_USER: ${{ secrets.HEROKU_POSTGRES_USER }} 
          POSTGRES_SERVER: ${{ secrets.HEROKU_POSTGRES_SERVER }} 
          POSTGRES_DATABASE_URI: ${{ secrets.HEROKU_POSTGRES_DATABASE_URI }} 
          DATASOURCE: ${{ secrets.HEROKU_DATASOURCE }} 
          POSTGRES_PASSWORD: ${{ secrets.HEROKU_POSTGRES_PASSWORD }} 
        run: printenv | grep 'POSTGRES_DB\|POSTGRES_USER\|POSTGRES_DATABASE_URI\|DATASOURCE\|POSTGRES_SERVER\|POSTGRES_PASSWORD' > .env
      - name: Show env
        run: cat .env
        